### PR TITLE
Cppcheck

### PR DESCRIPTION
**Pull request by VictorQRS**
This is merely a refactoring of existing code as an attempt to reduce code duplication.

I wanted to do more, like pass a static analyzer, but I won't be able to touch this code for a while, so I will deliver this right now, and, if possible, deliver the rest in a further date.

### CODE REVIEW

**Comment by claudiosegala** [comment]
@VictorQRS did you test it?

**Comment by VictorQRS** [comment]
@claudiosegala It compiles and runs just fine. About the results, I haven't checked, since I don't know what to expect from the samples. Are all the samples working?

**Comment by claudiosegala** [comment]
Yes, all samples are working. To test, verify:
Run the bytecode (.class)
And run with our JVM the same bytecode
Compete the results 

Are expected to work just the ones with arithmetic operations and switch. Others need object support which we don't have yet

**Comment by VictorQRS** [comment]
As it is not working, I will close this PR until I discover the causes and perhaps with another PR to do these tests automatically.

**Pull request closed without merging**
